insert into Team (Name, SimpleName)  values ('Olympique Lyonnais','Lyon')
insert into Team (Name, SimpleName)  values ('FC Nantes','Nantes')
insert into Team (Name, SimpleName)  values ('AS Monaco','Monaco')
insert into Team (Name, SimpleName)  values ('Bordeaux','Bordeaux')
insert into Team (Name, SimpleName)  values ('Paris SG','Paris')
insert into Team (Name, SimpleName)  values ('Caen','Caen')
insert into Team (Name, SimpleName)  values ('Metz','Metz')
insert into Team (Name, SimpleName)  values ('Lille','Lille')
insert into Team (Name, SimpleName)  values ('Martigues','Martigues')
insert into Team (Name, SimpleName)  values ('Marseille','Marseille')
insert into Team (Name, SimpleName)  values ('Lens','Lens')
insert into Team (Name, SimpleName)  values ('Montpellier','Montpellier')
insert into Team (Name, SimpleName)  values ('Le Havre','Le Havre')
insert into Team (Name, SimpleName)  values ('Strasbourg','Strasbourg')
insert into Team (Name, SimpleName)  values ('Sochaux','Sochaux')
insert into Team (Name, SimpleName)  values ('Angers','Angers')
insert into Team (Name, SimpleName)  values ('Toulouse','Toulouse')
insert into Team (Name, SimpleName)  values ('Cannes','Cannes')